# TOML file for ice cream mod! Ironically, the creator of this language is a co-founder of GitHub!
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/SuperHarmony910/modification-builder/issues/new" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="icecream" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${file.jarVersion}" #mandatory
# A display name for the mod
displayName="Who Wants Ice Cream?!" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="https://github.com/SuperHarmony910/modification-builder/issues/new" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/SuperHarmony910/modification-builder/releases/tag/v0.2.0-alpha" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="iceCream.png" #optional
# A text field displayed in the mod UI
credits="Thanks to TechnoVision @ https://www.youtube.com/channel/UC3n-lKS-MYlunVtErgzSFZg for the tutorial on modding and MrCrayfish for the inspiration on what can be made with these lines of code!" #optional
# A text field displayed in the mod UI
authors="SuperHarmony910" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
This is the first time I've ever modded Minecraft, and after a minimal effort of questioning my little sister, she wanted ice cream! So, I guess that's what I'm going to be doing for the first mod in Minecraft. :D
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.icecream]] #optional
# the modid of the dependency
modId="icecream" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory=true #mandatory
# The version range of the dependency
versionRange="[0.2.0,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side="CLIENT"
# Here's another dependency
[[dependencies.icecream]]
modId="icecream"
mandatory=true
versionRange="[0.1,]"
ordering="NONE"
side="BOTH"
