
name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
       
    - name: Run via Command Prompt to initiate execution permissions
      shell: cmd
    - name: Build with Gradle
      run:  gradlew build
    - name: Run with Gradle
      run: gradlew runClient
